# rails/tasks/users.yml
- name: Add the admin group
  sudo: true
  group: name=admin state=present

- name: Add the webapp user
  sudo: true
  user:
    name: "{{username}}"
    group: admin
    state: present
    shell: /bin/bash
    home: /home/{{username}}

# - name: Create the known_hosts SSH file
#   file: name=/home/{{username}}/.ssh state=directory group={{username}} user={{username}} mode=700
#   copy: name=/home/{{username}}/.ssh/known_hosts state=file group={{username}} user={{username}} mode=644

- name: Ensure sudoers contains root user
  sudo: true
  lineinfile:
    dest: /etc/sudoers
    backup: true
    state: present
    regexp: '^root'
    line: 'root ALL=(ALL:ALL) ALL'
- name: Ensure sudoers contains admin group
  sudo: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD:ALL'
- name: Ensure sudoers contains sudo group
  sudo: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) ALL'
- name: Ensure sudoers contains user
  sudo: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{username}}'
    line: '%{{username}} ALL=(ALL) NOPASSWD:ALL'
- name: Check and save the sudoers file
  sudo: true
  shell: visudo -q -c -f /etc/sudoers
