# common/tasks/packages.yml
- name: Update APT cache every hour
  sudo: true
  apt: update_cache=yes cache_valid_time=3600
- name: install htop
  sudo: true
  apt: pkg=htop state=latest
- name: install curl
  sudo: true
  apt: pkg=curl state=latest
- name: install git
  sudo: true
  apt: pkg=git-core state=latest
- name: Install python-software-properties
  sudo: true
  apt: pkg=python-software-properties state=latest
- name: Install unattended-upgrades
  sudo: true
  apt: pkg=unattended-upgrades
- name: Allow unattended security updates
  sudo: true
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp=^\s*(?!\/\/).* line='^(\s*)"Ubuntu precise-security";' state=present insertafter='Unattended-Upgrade::Allowed-Origins {'
- name: Configure automatic updates
  sudo: true
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic

